### ISSUE TITLE
`calc_mntd_ltable` crashes R session

### ISSUE THREAD

**Issue by EvoLandEco** [thijsjanzen/treestats#10]
Running `calc_mntd_ltable` several times will surely crash R session, may be related to #9 
```r
res <- DDD::dd_sim(c(0.5, 0.1, 20), 10)
L_extant <- res$L[res$L[, 4] == -1,]
replicate(100, treestats::mntd(L_extant))
```

**Comment by thijsjanzen** [comment]
> Caught an L table that 100 percent crashes R session
> 
> ```r
> this_L <-structure(c(10, 9.32573050613541, 8.20839978793837, 6.51136114987231,
>             5.7635943851298, 5.62821985771859, 5.49425863934385, 5.13832328855785,
>             4.84357598290745, 4.27390741214946, 3.75237929679556, 3.65399287146464,
>             2.75651201966894, 2.43593015102737, 1.98340674651101, 1.90094645245106,
>             1.54681945124979, 1.45742279303833, 1.45721180135205, 0.886248433098105,
>             0.804421248910581, -1, 2, 2, -9, 10, 2, 10, 4, -6, 3, 13, 4,
>             14, 23, 15, 21, 13, 20, 24, 30, 27, 2, 3, 7, -11, 12, 13, 14,
>             17, -18, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, -1,
>             -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
>             -1, -1, -1, -1), dim = c(21L, 4L))
> 
> # boom
> treestats::mntd(this_L)
> ```

That ltable looks very funky anyway, and also crashes l_to_phylo (both on master and develop).

It seems there are lineages missing - the third column does not have all numbers.

**Comment by thijsjanzen** [comment]
see https://github.com/thijsjanzen/treestats/issues/9#issuecomment-1132184667

Dropping extinct lineages from an Ltable is not valid by doing: 
```r
L_extant <- res$L[res$L[, 4] == -1,]
```

For instance, in the Ltable you posted:
```
           [,1] [,2] [,3] [,4]
 [1,] 10.0000000   -1    2   -1
 [2,]  9.3257305    2    3   -1
 [3,]  8.2083998    2    7   -1
 [4,]  6.5113611   -9  -11   -1
 [5,]  5.7635944   10   12   -1
 [6,]  5.6282199    2   13   -1
 [7,]  5.4942586   10   14   -1
 [8,]  5.1383233    4   17   -1
 [9,]  4.8435760   -6  -18   -1
[10,]  4.2739074    3   20   -1
[11,]  3.7523793   13   21   -1
[12,]  3.6539929    4   22   -1
[13,]  2.7565120   14   24   -1
[14,]  2.4359302   23   25   -1
[15,]  1.9834067   15   26   -1
[16,]  1.9009465   21   27   -1
[17,]  1.5468195   13   28   -1
[18,]  1.4574228   20   29   -1
[19,]  1.4572118   24   30   -1
[20,]  0.8862484   30   31   -1
[21,]  0.8044212   27   32   -1
```

We observe that species 26 has as parent, species 15. However, species 15 does not exist in the ltable. Similarly, species 11, 12 and 14 have parents -9, 10 and 10 respectively, which also don't exist in the pruned ltable (they are extinct). 

Thus the crash.

In https://github.com/thijsjanzen/treestats/commit/e19c547af14e66ed4caf1843aef695c53822ad3c on develop, I have added range checks, and this one does not crash R anymore, but yields a nice throw.

**Comment by EvoLandEco** [comment]
> see [#9 (comment)](https://github.com/thijsjanzen/treestats/issues/9#issuecomment-1132184667)
> 
> Dropping extinct lineages from an Ltable is not valid by doing:
> 
> ```r
> L_extant <- res$L[res$L[, 4] == -1,]
> ```
> 
> For instance, in the Ltable you posted:
> 
> ```
>            [,1] [,2] [,3] [,4]
>  [1,] 10.0000000   -1    2   -1
>  [2,]  9.3257305    2    3   -1
>  [3,]  8.2083998    2    7   -1
>  [4,]  6.5113611   -9  -11   -1
>  [5,]  5.7635944   10   12   -1
>  [6,]  5.6282199    2   13   -1
>  [7,]  5.4942586   10   14   -1
>  [8,]  5.1383233    4   17   -1
>  [9,]  4.8435760   -6  -18   -1
> [10,]  4.2739074    3   20   -1
> [11,]  3.7523793   13   21   -1
> [12,]  3.6539929    4   22   -1
> [13,]  2.7565120   14   24   -1
> [14,]  2.4359302   23   25   -1
> [15,]  1.9834067   15   26   -1
> [16,]  1.9009465   21   27   -1
> [17,]  1.5468195   13   28   -1
> [18,]  1.4574228   20   29   -1
> [19,]  1.4572118   24   30   -1
> [20,]  0.8862484   30   31   -1
> [21,]  0.8044212   27   32   -1
> ```
> 
> We observe that species 26 has as parent, species 15. However, species 15 does not exist in the ltable. Similarly, species 11, 12 and 14 have parents -9, 10 and 10 respectively, which also don't exist in the pruned ltable (they are extinct).
> 
> Thus the crash.
> 
> In [e19c547](https://github.com/thijsjanzen/treestats/commit/e19c547af14e66ed4caf1843aef695c53822ad3c) on develop, I have added range checks, and this one does not crash R anymore, but yields a nice throw.

Thanks! I also found out just now that directly dropping extinct lineages in L table will result in access violation in C++, because the largest lineage number exceeds the number of rows of the L table.

I'm planning to implement a function to calculate nearest taxon distance for every tip, I'll move on from here
