### ISSUE TITLE
(Probably) random error of `beta_statistic` at `develop`

### ISSUE THREAD

**Issue by EvoLandEco** [thijsjanzen/treestats#12]
I am unable to reproduce the error with a specific phylo object. `beta_statistic` seems to crash RStudio randomly. 

I tested this function using various sets of phylo objects, at first RStudio crashed on a specific set of phylo objects, when I tried to narrow down to a specific phylo, it crahsed several times and then didn't crash anymore, no matter how many replications I made since then. 

In this sense I can't be sure if it is a problem of the code or my own workspace. I'll update this issue if I have any news.

**Comment by thijsjanzen** [comment]
I believe this error was generated by an out-of-bounds violation in the beta_statistic rcpp code, triggered when calculating the statistic for a tree with only 2 tips. This has been resolved now by adding a throw detection and returning NA in that case.

Please feel free to verify with the develop branch and see if these crashes have now disappeared
