### ISSUE TITLE
about purging ed codes

### ISSUE THREAD

**Issue by EvoLandEco** [thijsjanzen/treestats#15]
The simulation of my package was relying on the  `l_to_newick_ed` and `l_to_newick_ed` functions in `treestats`, if they are not suitable in the `treestats` package, could I port these code into my own package?

**Comment by thijsjanzen** [comment]
Hi @EvoLandEco , I removed these codes as I felt these were not so generally applicable to any phylogeny, and only find specific use in your use case. 
Feel free to port these into your own package of course!
