### ISSUE TITLE
Inconsistent arguments

### ISSUE THREAD

**Issue by EvoLandEco** [thijsjanzen/treestats#16]
**Examples**
```r
imbalance_steps <- function(input_obj, normalize = FALSE)
```
```r
tot_coph <- function(phy, normalization = "none") 
```

In those balance stats functions some of them use `normalize` while the others use `normalization` as argument name, this makes it a bit confusing when using them.

**Comment by thijsjanzen** [comment]
Fixed in commit: 60f8d549b805839f06c5f106b09726dc587d4d88
