### ISSUE TITLE
Documentation of b1 function

### ISSUE THREAD

**Issue by EvoLandEco** [thijsjanzen/treestats#17]
**b1**
![image](https://github.com/thijsjanzen/treestats/assets/57348932/5e149c78-049c-4021-aff8-0c7574b80947)
**b2**
![image](https://github.com/thijsjanzen/treestats/assets/57348932/56788467-5734-4b5d-9b65-ecb225fa5731)
`b1` and `b2` have the same description, I think they should be different?

**Comment by thijsjanzen** [comment]
Well spotted! This was fixed two weeks ago in the develop branch, and brought to the master branch ~yesterday ish :) Should be fine now!
