### ISSUE TITLE
Segmentation fault due to polytomies

### ISSUE THREAD

**Issue by fstrijth** [thijsjanzen/treestats#23]
The following tree causes a crash:
(((((((((((394|87008|31.000000:10):1):0,((443|228842|25.000000:1,(310|322189|33.000000:9):0):4):0):3,(((167|281246|34.000000:5):0,(((39|594197|47.000000:7):4):7):0):12):0):8):0,((677|95737|14.000000:5):0,((((((((((299|95660|32.000000:8):1,(328|18227|34.000000:11):0):5):1,(529|82723|35.000000:18):0):4):0,(((((551|95698|20.000000:0,(((((((((52|288365|42.000000:3):2):2):9):1):0,((213|95338|31.000000:4):0,(211|95438|31.000000:4):0):2):2):0,(((((75|95233|42.000000:7):5):4):2):0,((187|87178|33.000000:5):3):1):1):3):0):4):0,((((((116|414351|33.000000:3):4):1,((200|322400|37.000000:10):2):0):3):1,((313|413957|34.000000:10):3):0):5):0):3):0,(((((((32|323647|45.000000:4):0,105|323758|44.000000:3):10):3):5):10):0,(((((((((((197|521440|33.000000:6):4):1):0,((((99|521891|41.000000:9):3):3,((185|108825|35.000000:7):2):0):3):1):2):0,(((((28|466137|53.000000:11):2):8):6):5):1):3):1,(572|228807|22.000000:6):0):1,(((((339|95414|28.000000:5):5):0,(((((433|87136|30.000000:10):0,(407|32014|30.000000:9):1):1,(((173|281345|33.000000:5):4):5):0):0,(453|87102|24.000000:5):0):1):0):1,((((((41|272766|51.000000:11):11):4):2):0,536|165288|25.000000:2):6):0):2):0):1):1,(((((45|108734|45.000000:5):4):6):3):14):0):0):0):0):3):0,(661|108674|17.000000:7):0):1):0,((((((((((399|512506|28.000000:1,(226|599622|36.000000:9):0):6):3):1,((514|301066|23.000000:3,(((((138|512486|33.000000:2,(((54|599178|44.000000:5):5):3):0):1):3):4):3):0):3):0):1,(561|512439|20.000000:4):0):3):0,((605|165228|19.000000:5):0,(((457|69396|26.000000:7):3):0,(((266|503559|31.000000:5):2):8):0):2):1):0,(((((413|301357|27.000000:7):3):0,(621|69155|20.000000:2,(484|503855|26.000000:8):0):1):0,((((368|439440|27.000000:5):0,426|165159|24.000000:2):2):3):0):4):0):3):0,(((((((((((64|95583|43.000000:7):1,(((((0|95276|54.000000:3):4):1,((11|466043|54.000000:3,(2|288069|56.000000:5):0):5):0):6):5):0):6):3):0,((((((23|322084|49.000000:6):4):7):3):3):0,(((102|193327|37.000000:5):0,249|95340|33.000000:1):6):0):0):4):1,((((((190|414267|33.000000:5):5):0,(291|86978|30.000000:5):2):1):0,(((136|281200|36.000000:6):6):0,((94|87326|38.000000:6):7):1):2):1):0):5):0,(((565|470003|19.000000:2,((219|69431|32.000000:5):10):0):1):0,(((((256|64731|44.000000:18):5):3):0,((437|69190|28.000000:8):2):0):2):0):0):5):0,((((((((282|85117|32.000000:7):0,422|272521|26.000000:1):5):1):0,((326|177676|28.000000:5):2):2):2):0,((208|108831|30.000000:3):10):0):6):0):1):1):0):0):1):2):4):0,((((((((((242|193636|30.000000:4):0,(274|193465|31.000000:4,(206|193447|31.000000:4):0):1):1):0,((((34|246336|47.000000:6):4):6):6):0):3):4):10):0,((((((((((179|238083|35.000000:7):10):0,(392|234586|27.000000:6):3):1):0,(601|521635|20.000000:2,((((((((((49|39877|51.000000:12):4):6):2,((194|551545|36.000000:0,(70|216980|43.000000:7):0):9):0):1):1,(((68|48509|50.000000:14):6):5):0):3):2):0,487|48568|22.000000:2):2):0):1):3):1,(((((((((((6|415093|56.000000:7):0,58|18129|51.000000:2):12):0,112|322267|39.000000:2):6):4):2):4,(((284|526996|30.000000:5):0,(((81|395224|39.000000:4):5):5):0):4):0):2):3):3):0):2):3):0,(((((((((506|17936|21.000000:0,(((((((((62|134502|42.000000:6):0,133|83993|38.000000:2):6):0,(89|31799|39.000000:5):4):0,(131|193791|39.000000:9):0):3):1):0,((204|229031|31.000000:4):0,((151|466088|43.000000:14):1):1):1):5):0):4):0,(((((((((9|9112|53.000000:7):3):3):5):5):4):4):0,((((4|281217|55.000000:5):6):9):10):3):4):1):2):3):0,(((((370|11307|26.000000:4):5):2):0,((((((((((263|136171|37.000000:11):1,((175|445239|43.000000:15):3):0):2):3,(((((36|336667|48.000000:7):5):5):7):4):0):2):0,(((((((319|295848|32.000000:2,(125|83000|35.000000:5):0):0,((((15|41310|51.000000:7):8):4):2):0):6):1,(347|156835|32.000000:9):0):2):0,(((232|457032|30.000000:4):0,(((161|404298|35.000000:0,(84|404212|40.000000:5):0):6):3):0):3):2):3):0):1,((411|534205|28.000000:8):3):0):1):0,(((((519|135886|26.000000:3,((302|83534|34.000000:10):1):0):1,(372|24220|28.000000:6):0):5):0,(((481|295825|22.000000:3,(448|296031|26.000000:7):0):1):1,((((159|457422|33.000000:4):6):0,(((238|283443|32.000000:6):0,(((26|426819|46.000000:4):3):12):1):3):0):6):0):0):0,(517|457433|38.000000:21):0):1):1):0):0,((((165|17954|36.000000:7):1,470|95514|28.000000:0):10):3):0):3):0,(639|281184|29.000000:17):0):2):2,(((((((((92|86964|37.000000:4):0,127|95225|35.000000:2):3):3):4):0,(((169|17875|49.000000:20):0,331|414146|30.000000:1):6):0):5):5):5):0):0):0):6):0,735|455284|2.000000:0):0):2,((((((((21|255070|51.000000:8):18):6):6):1,(((109|556552|49.000000:18):0,636|556675|34.000000:3):19):0):5):0,((((((((((409|83199|27.000000:6):0,((((253|79564|30.000000:2,((30|484771|48.000000:6):14):0):2):4):0,((271|79913|32.000000:7):3):0):1):3):1):0,595|79940|20.000000:3):3):3,(((563|37306|27.000000:11):2):3):0):2):0,(((((460|484742|36.000000:17):2,608|484743|17.000000:0):4):2,(((((512|79598|25.000000:8):0,611|484502|19.000000:2):4):0,(((((509|83282|24.000000:7):0,(((((192|554004|32.000000:5):4):5):0,((((156|24302|34.000000:5):4):2):5):0):1,(((435|83716|24.000000:4):1):2):0):0):1,(((((((77|316021|40.000000:5):6):3):4):5):0,((((((((279|11317|34.000000:9):0,304|166416|27.000000:2):1):0,(((((((((((17|79887|48.000000:4):3):12):0,(154|24347|34.000000:5):0):1):0,260|11304|32.000000:4):2):0,(258|11483|29.000000:3):0):2):0,416|295969|28.000000:4):0,(((144|419461|36.000000:7):3):2):0):0):4):1,(((97|409553|39.000000:7):6):7):0):1):0,(446|441862|25.000000:6):1):1):1):0):1,((((120|83535|34.000000:4):3):9):3):0):2):0):2):0):1):1):2):0):7):0,((730|98366|2.000000:2,(((((((((592|42452|21.000000:6):4):0,((554|419236|27.000000:11):5):0):1,(((177|580064|34.000000:6):13):5):0):2):0,712|585365|10.000000:2):6):0,((722|373440|7.000000:5):0,((((706|260245|7.000000:0,(((((((336|319198|30.000000:0,(118|26053|35.000000:5):0):7):3):4):0,696|255195|17.000000:1):0,(((((((224|528823|31.000000:4):0,386|35352|27.000000:0):6):0,545|291178|21.000000:0):0,((((240|254913|46.000000:20):2):0,(296|260250|28.000000:4):0):3):0):1,(((171|113656|33.000000:4):5):4):0):4):0):9):0):3):0,((((((((((19|258120|58.000000:15):8):2):0,221|27926|36.000000:3):6):3):7):8):2):3):0):2):0):0):2):0):0):0,(710|28982|11.000000:4):7,727|450414|4.000000:4):0;

The R code:
> library(treestats)
Loading required package: Rcpp
> library(ape)
> tree = read.tree('combined.nwk')
> calc_all_stats(tree)

 *** caught segfault ***
address 0x12, cause 'memory not mapped'
Segmentation fault

**Comment by thijsjanzen** [comment]
For some statistics, the code implicitly assumes the trees to be binary - often this is for statistics that assume this (for instance the Colless statistic measures L - R, where L is the number of tips attached to the left daughter branch at a node, and R the number of tips attached to the right daughter branch at a node. This calculation becomes impossible in the case of polytomies).

Commit 3b6d29e70a9ab64834f449ef50a3f91b59c26c8b resolves this by adding preliminary checks to all functions, where the code checks a tree to be binary (if required) and/or ultrametric (if required).
