### ISSUE TITLE
Compilation error due to wrong c++ standard

### ISSUE THREAD

**Issue by EvoLandEco** [thijsjanzen/treestats#27]
Sometimes, at least on Windows, compiler might use a wrong flag `-std=gnu++11`, which causes compilation error as the current implementation incorporates features introduced at least from C++14 and 17.

Adding in `Makevars.win` the following flag fixes the error:

```r
CXX_STD = CXX17
```

Or perhaps `CXX20` is needed.

**Comment by thijsjanzen** [comment]
Fixed here: dadc04b059ce262eda5c141813cc618c4969e5e5
