### ISSUE TITLE
`l_to_phylo` stuck on arbitrary L table

### ISSUE THREAD

**Issue by EvoLandEco** [thijsjanzen/treestats#7]
```r
test_l<-DDD::dd_sim(c(0.5,0.1,20),10)
test_l<-test_l$L
phylo<-treestats::l_to_phylo(test_l,drop_extinct = T)
# stuck here, R session not responding
```
The issue can be easily reproduced by an arbitrary L table created by a DDD simulation.
The reverse-timescale version in #6  has the same issue

**Comment by EvoLandEco** [comment]
Further tests indicate that `l_to_phylo` cannot process L table containing extinct lineage(s)

**Comment by EvoLandEco** [comment]
``` r
ltable <- structure(c(4.2, 4.2, 2.374042, 1.69827, 1.586264, 1.114531, 
            1.085625, 0.701408, 0.608568, 0.520556, 0.459367, 0, -1, 2, -1, 
            2, -4, -6, 2, -6, -9, -7, -1, 2, 3, -4, 5, -6, -7, 8, -9, -10, 
            -11, 1.1, 0.31, 1.863526, 0.272869, 0.429045, -1, -1, -1, -1, 
            -1, -1), .Dim = c(11L, 4L))
```
Testing `treestats::l_to_phylo` against `DDD::L2phylo`. This is the correct tree: 
```r
plot(DDD::L2phylo(ltable,dropextinct = T))
```

![](https://i.imgur.com/LaTlgvS.png)

This one by `treestats::l_to_phylo(ltable,drop_extinct = T)` is missing t8
``` r
plot(treestats::l_to_phylo(ltable,drop_extinct = T))
```

![](https://i.imgur.com/0E5Uffs.png)

This one is also generated by `treestats::l_to_phylo(ltable,drop_extinct = T)`, replicate this code can result in two different trees, weird.
![image](https://user-images.githubusercontent.com/57348932/167396125-defd5f31-f289-4def-9369-a5e2bd053cf6.png)

``` r
plot(DDD::L2phylo(ltable,dropextinct = F))
```

![](https://i.imgur.com/ZmUi3AY.png)



``` r
plot(treestats::l_to_phylo(ltable,drop_extinct = F))
```

![](https://i.imgur.com/sUZ940U.png)

If set `drop_extinct = F`, `treestats::l_to_phylo` works fine.

I guess it is the drop_extinct part causes the problem. I'll check the code again, and perhaps a workaround is to just generate the whole tree without dropping extinct lineages, and let `ape` drop the tips later in the R code.

<sup>Created on 2022-05-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by thijsjanzen** [comment]
This issue seems resolved now, code above now generates the right tree.

Does the issue referred in https://github.com/thijsjanzen/treestats/pull/6#issuecomment-1121540827 still arise? I do not have the code to test this specific case @EvoLandEco

**Comment by EvoLandEco** [comment]
> This issue seems resolved now, code above now generates the right tree.
> 
> Does the issue referred in [#6 (comment)](https://github.com/thijsjanzen/treestats/pull/6#issuecomment-1121540827) still arise? I do not have the code to test this specific case @EvoLandEco

I haven't got time to further examine this last week, I'll have a look now.

**Comment by EvoLandEco** [comment]
```r
test_l <- structure(c(10, 10, 8.65720237313422, 7.52112256662757, 4.94259451955203, 
            4.02141458501139, 3.18867978010257, 3.0414300418969, 2.53271705998738, 
            1.84976965035132, 1.31034753274349, 1.26110486362692, 0.806069840362717, 
            0.592701463871053, 0.53552669331763, 0, -1, 2, 3, 3, -1, 3, 4, 
            -6, 5, 5, 10, 8, 12, 13, -1, 2, 3, 4, 5, -6, 7, 8, -9, 10, 11, 
            12, 13, 14, 15, -1, -1, -1, -1, 1.26868367092781, -1, -1, -1, 
            -1, 0.0527305518860519, -1, -1, -1, -1, -1), .Dim = c(15L, 4L
            ))
phy1<-treestats::l_to_phylo(test_l,drop_extinct = T)
```

with this case we always get a `Error in l_to_newick(ltab, drop_extinct) : Look up failed 00`
this is a test I added in, please check out my branch and have a try

**Comment by EvoLandEco** [comment]
@thijsjanzen In `develop` :
```r
# test whether
test_all_equal <- function(drop = FALSE) {
  res <- DDD::dd_sim(c(0.5, 0.1, 20), 10)
  phy1 <- treestats::l_to_phylo(res$L, drop_extinct = drop)
  phy2 <- DDD::L2phylo(res$L, dropextinct = drop)
  out <- all.equal(sum(phy1$edge.length),
                   sum(phy2$edge.length),
                   tolerance = 0.00001)
  return(out)
}

# test drop_extinct = F
out_list <- replicate(1000, test_all_equal(FALSE))
FALSE %in% out_list
# all trees are identical
# [1] FALSE

# test drop_extinct = T
out_list <- replicate(100, test_all_equal(TRUE))
FALSE %in% out_list
# still generates error, but 0 1 not 0 0
# Error in l_to_newick(ltab, drop_extinct) : Look up failed 1 0
```


I believe now `drop_extinct = F` works perfectly, but `drop_extinct = T` still needs deeper investigation.

**Comment by EvoLandEco** [comment]
I printed out the remaining L table:
```r
Error in l_to_newick(ltab, drop_extinct) : Look up failed 1 0
-1.000000 -1.000000 2.000000 10.000000 
0.000000 0.000000 -1.000000 3.545217
```

**Comment by thijsjanzen** [comment]
Done
