### ISSUE TITLE
inconsistent results from `treestats::mntd` between using ltable and phylo

### ISSUE THREAD

**Issue by EvoLandEco** [thijsjanzen/treestats#9]
On `master`, `calc_mntd_ltable`'s output is inconsistent with `calc_mntd_stat`'s

``` r
res <- DDD::dd_sim(c(0.5, 0.1, 20), 10)
# get a phylo with only extant lineages
phy <- treestats::l_to_phylo(res$L, drop_extinct = T)
# get a ltable with only extant lineages
L_extant <- res$L[res$L[, 4] == -1,]

# this should call calc_mntd_stat
treestats::mntd(phy)
#> [1] 4.689622

# this should call calc_mntd_ltable
treestats::mntd(L_extant)
#> [1] 6.042044
```
I can verify that `calc_mntd_stat` is consistent with `picante::mntd`, so `calc_mntd_ltable` is wrong
``` r
# test whether calc_mntd_stat equals picante::mntd
test_mntd_equal <- function() {
  res <- DDD::dd_sim(c(0.5, 0.1, 20), 10)
  phy <- treestats::l_to_phylo(res$L, drop_extinct = T)
  nti1 <- treestats::mntd(phy)
  dis <-ape::cophenetic.phylo(phy)
  samp <- data.frame()
  samp <- rbind(samp, rep(1, length(phy$tip.label)))
  colnames(samp) <- phy$tip.label
  rownames(samp) <- "comm"
  nti2 <- picante::mntd(samp, dis)

  out <- all.equal(nti1,
                   nti2,
                   tolerance = 0.00001)
  return(out)
}

# test 1000 replicates
out_list <- replicate(1000, test_mntd_equal())
FALSE %in% out_list
#> [1] FALSE
```

<sup>Created on 2022-05-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by thijsjanzen** [comment]
This goes wrong, because simply dropping species that are extinct distorts the ltable, such that it no longer forms a consistent table. The following works however:

```r
res <- DDD::dd_sim(c(0.5, 0.1, 20), 10)
# get a phylo with only extant lineages
phy <- treestats::l_to_phylo(res$L, drop_extinct = TRUE)
# get a ltable with only extant lineages
L_extant <- res$L[res$L[, 4] == -1,]
L_two <- treestats::phylo_to_l(phy)

treestats::mntd(phy)
treestats::mntd(L_two) # these are now the same! We have dropped extinct correctly

treestats::mntd(L_extant) # this ltable is malformed

**Comment by EvoLandEco** [comment]
> This goes wrong, because simply dropping species that are extinct distorts the ltable, such that it no longer forms a consistent table. The following works however:
> 
> ```r
> res <- DDD::dd_sim(c(0.5, 0.1, 20), 10)
> # get a phylo with only extant lineages
> phy <- treestats::l_to_phylo(res$L, drop_extinct = TRUE)
> # get a ltable with only extant lineages
> L_extant <- res$L[res$L[, 4] == -1,]
> L_two <- treestats::phylo_to_l(phy)
> 
> treestats::mntd(phy)
> treestats::mntd(L_two) # these are now the same! We have dropped extinct correctly
> 
> treestats::mntd(L_extant) # this ltable is malformed
> ```

My bad, I misunderstood its usage here, thanks for your explanation
